### ISSUE TITLE
Error when trying to format

### ISSUE THREAD

**Issue by lanza** [yatli/fsharp-language-server#10]
```
DocumentFormatting: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at FSharpLanguageServer.Program.LSP-Types-ILanguageServer-DocumentFormatting@1103-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

```

**Comment by yatli** [comment]
@lanza issue fixed. try again?
