### ISSUE TITLE
Opening an FSX file gives an error when using .NET Core 3.1

### ISSUE THREAD

**Issue by PhilT** [yatli/fsharp-language-server#15]
Since upgrading to .NET Core 3.1 I've noticed that FSX files no longer compile. I get the following error:

```
[undefined] [E] parameter: System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
   at System.Reflection.AssemblyName.nInit()
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at FSharp.Compiler.SimulatedMSBuildReferenceResolver.SimulatedMSBuildResolver@28.FSharp-Compiler-ReferenceResolver-Resolver-Resolve(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, FSharpFunc`2 logMessage, FSharpFunc`2 logWarningOrError) (Code=SR001)
```

To be fair it's been a while since I loaded an FSX file so I'm not sure if the break is with Core 3.1 or a regression that was introduced in coc-fsharp.

**Comment by yatli** [comment]
Could you elaborate on your setting? I cannot repro from my side.
Also, could you update to the latest version? I've made some changes to the project analyzer recently.

**Comment by PhilT** [comment]
Here's my CocInfo. I'm running on Windows 10. Even with a blank or single line `let i = 0` I get the above error.

```
## versions

vim version: NVIM v0.4.3
node version: v13.9.0
coc.nvim version: 0.0.78-fc983ce6dd
term: vtpcon
platform: win32

## Output channel: fsharp

Listening on stdin

Couldn't find System.ComponentModel.Composition.dll in C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server
Add workspace root c:\Users\Phil\code\sandbox
output: 3.1.102 [C:\Program Files\dotnet\sdk]
dotnet pack folders: ["C:\Program Files\dotnet\packs"]
New configuration {
  "trace": {
    "server": "off"
  },
  "project": {
    "define": [],
    "otherFlags": [],
    "includeCompileBefore": false,
    "additionalSourceFiles": [],
    "overrideReferences": []
  },
  "codelens": {
    "references": true
  },
  "analysis": {
    "unusedDeclaration": true
  }
}
analyzeLater: c:\Users\Phil\code\sandbox\test.fsx
Creating project options for script test.fsx
c:\Users\Phil\code\sandbox\test.fsx.fsproj: 
  ProjectFileName: "c:\Users\Phil\code\sandbox\test.fsx.fsproj"
  SourceFiles: [|"c:\Users\Phil\code\sandbox\test.fsx"|]
  ReferencedProjects: []
  OtherOptions: [|"-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\FSharp.Core.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\Microsoft.CSharp.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\Microsoft.VisualBasic.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\Microsoft.Win32.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.AppContext.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Buffers.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Collections.Concurrent.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Collections.Immutable.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Collections.NonGeneric.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Collections.Specialized.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Collections.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.Annotations.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.DataAnnotations.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.EventBasedAsync.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.TypeConverter.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ComponentModel.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Configuration.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Console.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Core.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Data.Common.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Data.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.Contracts.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.Debug.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.DiagnosticSource.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.FileVersionInfo.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.Process.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.StackTrace.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.TextWriterTraceListener.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.Tools.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.TraceSource.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Diagnostics.Tracing.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Drawing.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Drawing.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Dynamic.Runtime.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Globalization.Calendars.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Globalization.Extensions.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Globalization.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.Compression.FileSystem.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.Compression.ZipFile.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.Compression.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.FileSystem.DriveInfo.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.FileSystem.Primitives
.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.FileSystem.Watcher.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.FileSystem.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.IsolatedStorage.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.MemoryMappedFiles.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.Pipes.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.UnmanagedMemoryStream.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.IO.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Linq.Expressions.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Linq.Parallel.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Linq.Queryable.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Linq.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Http.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.HttpListener.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Mail.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.NameResolution.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.NetworkInformation.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Ping.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Requests.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Security.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.ServicePoint.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.Sockets.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.WebClient.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.WebHeaderCollection.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.WebProxy.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.WebSockets.Client.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.WebSockets.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Net.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Numerics.Vectors.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Numerics.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.ObjectModel.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.DispatchProxy.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Emit.ILGeneration.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Emit.Lightweight.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Emit.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Extensions.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Metadata.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.TypeExtensions.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Reflection.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Resources.Reader.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Resources.ResourceManager.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Resources.Writer.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.CompilerServices.VisualC.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Extensions.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Handles.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.InteropServices.RuntimeInformation.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.InteropServices.WindowsRuntime.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.InteropServices.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Loader.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Numerics.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Serialization.Formatters.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Serialization.Json.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Serialization.Primitives.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Serialization.Xml.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.Serialization.dll";
  "-r:C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server\System.Runtime.dll";
  ...|]
  LoadTime: 16/04/2020 10:51:02
  ExtraProjectInfo: <null>
  IsIncompleteTypeCheckEnvironment: false
  OriginalLoadReferences: []
  ExtraProjectInfo: <null>
  Stamp: <null>
  UnresolvedReferences: Some UnresolvedReferencesSet []
  UseScriptResolutionRules: true

```

**Comment by yatli** [comment]
Could be Windows-specific.
Related issues:
https://github.com/fsprojects/fsharp-language-server/issues/29
https://github.com/dotnet/fsharp/issues/6161

Hmm I remember having no trouble with it on Windows. Will look into it when I boot Windows. Thanks!

**Comment by yatli** [comment]
FSAC related and I believe this problem is automatically solved now.
